### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by boozook** [pd-rs/get-playdate-sdk#1]
Determine how to install SDK on windows (headless, CI).

**Comment by louiidev** [comment]
this would be nice, interested in playing around with this but only have windows

**Comment by boozook** [comment]
@louisgjohnson That would be great! Just try install SDK with bash (or any available shell) without interaction with UI of installer. We have no anything but shell on CI.
Also will be cool investigate kind of installer and what it can - parameters of execution, etc..

I can take my wife's laptop with win7 and investigate about. I'll try this evening or tomorrow.

**Comment by boozook** [comment]
I tried on windows and have no Idea how to install it on headless system.

But one hacky idea I have is to write powershell script with async loop where tell OS globally fire key event (simulate Enter key-press) to accept & continue installer's UI dialogue. That's really not good but possible.
Imho, we should give up on this idea and wait Panic's solution with cli-installer.

Second my idea is to try to use gnu toolchain with SDK for linux on windows. That's seems more realistic.

**Comment by StevenEBarbaro** [comment]
Assuming WinGet's available I've had success with `winget install Panic.PlaydateSDK --silent --accept-source-agreements`
